- name: test
  hosts: webserver
  tasks:
    #-------------install nginx---------
    - name: install nginx
      apt:
        name: nginx
        state: present
    #-------------install node---------
    - name: add apt key for nodesource
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: add repo for nodesource
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main"
        update_cache: yes

    - name: install nodejs
      apt: name=nodejs
    #-------------install pm2---------
    - name: pm2
      npm: name=pm2 global=yes
